# Main configuration file for BatchFarming
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically in this file when upgrading.

# Max counts of run at the same time [int] (default: 3)
max-count: 3

# Maximum step count of block placing at once [int] (default: 9)
max-step: 9

# The amount of height increasing in each step [float] (default: 0.4)
rise-per-step: 0.4

# Whether to rotate clockwise [boolean] (default: true)
clockwise: true