# BatchFarming 플러그인을 위한 고급 설정 파일
# 이 설정들 중 일부는 안전하지만, 또 다른 것들은 잘못 수정했을 경우 서버에 오류가 발생할 수 있습니다
# 새로운 설정/기본은 이 파일을 업그레이드할 때 자동으로 나타나지 않습니다

# 동시에 실행 가능한  [int] (기본값: 3)
max-count: 3

# 한 번에 설치하는 블록의 최대 수 [int] (기본값 : 9)
max-step: 9

# 각 단계에서 증가하는 높이 [float] (기본값 : 0.4)
rise-per-step: 0.4

# 시계 방향으로 회전할지 여부 [boolean] (기본값 : true)
clockwise: true